# Javascript Node CircleCI 2.1 configuration file
# Check https://circleci.com/docs/2.1/language-javascript/ for more details
version: 2.0
jobs:
 build:
   docker:
     # specify the version you desire here
     - image: circleci/node:10
   working_directory: ~/repo
 
   steps:
     - checkout
 
     # Download and cache dependencies
    
     - run: cd Frontend/ && yarn install && yarn build
 

    
     - persist_to_workspace:
         root: .
         # Must be relative path from root
         paths:
           - build/*

 deploy:
   docker:
     - image: circleci/python:3.6

   work_directory: /tmp/my-project
   steps:
     - attach_workspace:
         at: /tmp/my-project

     - run:
         name: Install AWS CLI
         command: pip install awscli --user

     - run:
         name: Deploy to S3 if the build is successful
         command: ~/.local/bin/aws s3 sync --acl public-read /tmp/my-project/build/ s3://derek-coffee-shop-2020 --delete
       
     - run:
         name: Invalidate Cloudfront distribution
         command: ~/.local/bin/aws cloudfront create-invalidation --distribution-id E9APMWY68027J --paths "/*"
 
workflows:
 version: 2
 build-deploy:
   jobs:
     - build
     - deploy:
         requires:
           - build